model:
  name: resnet50                    # Options: resnet18, resnet34, resnet50, resnet101, vgg16, vgg19, densenet121, densenet169, efficientnet_b0
  pretrained: true

training:
  batch_size: 32
  epochs: 20
  
  loss:
    name: CrossEntropyLoss          # Options: CrossEntropyLoss, FocalLoss
    # For FocalLoss, you can add:
    # alpha: 1.0
    # gamma: 2.0
  
  optimizer:
    name: Adam                      # Options: Adam, SGD, AdamW
    lr: 0.001
    weight_decay: 1e-4
    # For SGD, you can add:
    # momentum: 0.9
  
  scheduler:
    name: StepLR                    # Options: StepLR, CosineAnnealingLR, ReduceLROnPlateau, null (for no scheduler)
    step_size: 10
    gamma: 0.1
    # For CosineAnnealingLR:
    # T_max: 50
    # For ReduceLROnPlateau:
    # factor: 0.1
    # patience: 10

transforms:
  resize: 256
  crop_size: 224
  horizontal_flip: true
  color_jitter: true
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1
  rotation: true
  rotation_degrees: 10
  mean: [0.485, 0.456, 0.406]       # ImageNet normalization
  std: [0.229, 0.224, 0.225]